### ISSUE TITLE
[RFE] Support Oracle Kubernetes Engine (OKE)

### ISSUE THREAD

**Issue by chessbyte** [ManageIQ/manageiq-providers-oracle_cloud#31]
- [x] Provider (https://github.com/ManageIQ/manageiq-providers-oracle_cloud/pull/30)
- [x] Icon (https://github.com/ManageIQ/manageiq-decorators/pull/53)
- [x] Capabilities Matrix (https://github.com/ManageIQ/manageiq-documentation/pull/1595)
- [x] Documentation (https://github.com/ManageIQ/manageiq-documentation/pull/1596)
- [x] Demo (https://youtu.be/SDF7ORfLvyc)

**Comment by Fryguy** [comment]
Done!
