### ISSUE TITLE
Public/Private Key should be API keys?

### ISSUE THREAD

**Issue by imphocused** [ManageIQ/manageiq-providers-oracle_cloud#58]
Which public/private key is referred to when configuring the Oracle Cloud Compute provider? There is no place (that I see) where these are stored per user in the Oracle dashboard, only API keys.

**Comment by agrare** [comment]
Hello @imphocused, when you generate an API Key you get a public/private key pair:
![image](https://user-images.githubusercontent.com/12851112/167474996-0c32e380-a3e0-4046-8a00-03564ed48957.png)

**Comment by imphocused** [comment]
🤦‍♂️  I spent more time than I'm willing to admit overlooking that. I had auth tokens and consumer keys, and only saw thought about ssh keys when creating instances.

thank you
