### ISSUE TITLE
Oracle Cloud provider shows Forbidden after successful verification

### ISSUE THREAD

**Issue by imphocused** [ManageIQ/manageiq-providers-oracle_cloud#59]
Hello,

After creating a new API keypair (thanks!) I'm able to successfully verify the connection, but after saving, the provider fails to authenticate:

Last Refresh Status

Error - Less Than A Minute Ago
{ 'message': 'Forbidden', 'status': 403, 'code': 'Forbidden', 'opc-request-id': '2086A74374A247729EA710BFD1BD8B99/61F...

![Screen Shot 2022-05-09 at 2 52 06 PM](https://user-images.githubusercontent.com/501310/167487065-2c3b3b04-b101-40a4-a159-4068623d70f1.png)

The same credentials work fine in the oci-cli. Unfortunately there is little/no reference to this error in the docker console/log output

**Comment by agrare** [comment]
Hey @imphocused can you post the evm.log for the refresh that has this error?  Everything from `Refreshing all targets...` to `Refreshing all targets...Complete`

**Comment by imphocused** [comment]
Attached (with ocid changed)

[evm.log](https://github.com/ManageIQ/manageiq-providers-oracle_cloud/files/8679800/evm.log)

**Comment by agrare** [comment]
Perfect thanks @imphocused here is the full backtrace:
```
[----] E, [2022-05-12T03:38:19.957186 #8846:2b2420c0794c] ERROR -- evm: [OCI::Errors::ServiceError]: Forbidden  Method:[block (2 levels) in <class:LogProxy>]
[----] E, [2022-05-12T03:38:19.957556 #8846:2b2420c0794c] ERROR -- evm: /opt/manageiq/manageiq-gemset/gems/oci-2.16.0/lib/oci/api_client.rb:478:in `handle_non_success_response'
/opt/manageiq/manageiq-gemset/gems/oci-2.16.0/lib/oci/api_client.rb:390:in `call_api_inner'
/opt/manageiq/manageiq-gemset/gems/oci-2.16.0/lib/oci/api_client.rb:143:in `block in call_api'
/opt/manageiq/manageiq-gemset/gems/oci-2.16.0/lib/oci/api_client.rb:146:in `call_api'
/opt/manageiq/manageiq-gemset/gems/oci-2.16.0/lib/oci/database/database_client.rb:9860:in `block in list_autonomous_databases'
/opt/manageiq/manageiq-gemset/gems/oci-2.16.0/lib/oci/retry/retry.rb:24:in `make_retrying_call'
/opt/manageiq/manageiq-gemset/gems/oci-2.16.0/lib/oci/database/database_client.rb:9859:in `list_autonomous_databases'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-oracle_cloud-733aa46b3353/app/models/manageiq/providers/oracle_cloud/inventory/collector.rb:58:in `block in oracle_databases'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-oracle_cloud-733aa46b3353/app/models/manageiq/providers/oracle_cloud/inventory/collector.rb:57:in `each'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-oracle_cloud-733aa46b3353/app/models/manageiq/providers/oracle_cloud/inventory/collector.rb:57:in `flat_map'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-oracle_cloud-733aa46b3353/app/models/manageiq/providers/oracle_cloud/inventory/collector.rb:57:in `oracle_databases'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-oracle_cloud-733aa46b3353/app/models/manageiq/providers/oracle_cloud/inventory/parser.rb:56:in `databases'
/opt/manageiq/manageiq-gemset/bundler/gems/manageiq-providers-oracle_cloud-733aa46b3353/app/models/manageiq/providers/oracle_cloud/inventory/parser.rb:11:in `parse'
```

It makes it through most of the collections but fails on collecting databases, it appears that the API Key you've provided does not have sufficient permissions to list oracle and mysql type databases.

**Comment by imphocused** [comment]
Thank you for taking a look, I appreciate the feedback. I've reached out to Oracle, as their support says they can give more detail on the error provided in the 'opc-request-id' response. 

`{ 'message': 'Forbidden', 'status': 403, 'code': 'Forbidden', 'opc-request-id': '2EECC402E8A940B88A72D4FC90919646/CD022E0222526F223FBAF9D9EE20E448/B158AF7DB811D744193DCBF2AE3F0AA6' }`


My tenancy (root tenancy) only has my sole account which is an Administrator.  The attached logs show these commands working successfully from the 'oci' command.

[oci_output_2022-05-12-1256.log](https://github.com/ManageIQ/manageiq-providers-oracle_cloud/files/8681580/oci_output_2022-05-12-1256.log)

- Is there a way to debug and get the actual urls/calls being made?
- Are there any 'oci' commands I can/should try to compare results?

ManageIQ Morphy
Version morphy-1.20220210224352_1e24154

**Comment by agrare** [comment]
Thanks @imphocused we get fetch both types of databases, MySQL and Oracle Autonomous Databases.  Your OCI command only tried to list mysql ones.  I don't have the `oci` command locally but try listing autonomous databases.

**Comment by agrare** [comment]
> Is there a way to debug and get the actual urls/calls being made?

@imphocused That is a great question, we should have a `log/oracle.log` with the API calls being made to cloud.oracle.com.  I will work on adding this now.

**Comment by imphocused** [comment]
The log I provided shows the 'autonomous-databases' as the first command tried, and mysql as the second. Both went through successfully. After a few days of back and forth with Oracle support, the best they could narrow it down to was:

> (A) 403 NotAllowedThis operation must be directed at the home region.
> (B) 403 NotAuthorizedYou do not have authorization to update one or more of the fields included in this request.
> (C) 403 SignUpRequiredThis operation requires opt-in before it may be called.
> have you tried this in you home region?
> Additionally, please make sure that you have authorization to perform the task.
> And lastly,Have you seen the option somewhere in the process, for opt-in before attempting this task

**Comment by agrare** [comment]
Okay thanks @imphocused I think the best course of action would be to grab the latest devel appliance image that includes https://github.com/ManageIQ/manageiq-providers-oracle_cloud/pull/62, set the log level for the oracle logger to debug, and re-run the refresh to see the exact API call being made.
